-- Cuentas +IVA (Factura A) — espeja cuentas_sin_iva. Se vinculan a la forma de
-- pago "Transferencia (Factura A)" (transferencia_blanco) por canal, igual que
-- cuentas_sin_iva se vincula a "Transferencia Directa" (transferencia_negro).
create table if not exists public.cuentas_con_iva (
  id         integer generated by default as identity primary key,
  nombre     text not null,
  cbu        text not null default '',
  alias      text not null default '',
  created_at timestamptz not null default now(),
  tipo       text not null default 'CBU' check (tipo = any (array['CBU'::text, 'CVU'::text, 'deposito'::text])),
  cuit       text,
  banco      text
);

alter table public.cuentas_con_iva enable row level security;

drop policy if exists "public read" on public.cuentas_con_iva;
create policy "public read" on public.cuentas_con_iva for select to public using (true);

alter table public.canales
  add column if not exists cuenta_con_iva_id integer
  references public.cuentas_con_iva(id) on delete set null;
