CREATE TABLE comunidad_fotos (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  url_instagram TEXT NOT NULL,
  thumbnail_url TEXT,
  caption       TEXT,
  username      TEXT,
  permalink     TEXT,
  orden         INTEGER DEFAULT 0,
  activo        BOOLEAN DEFAULT true,
  created_at    TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE comunidad_fotos ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read_comunidad ON comunidad_fotos
  FOR SELECT
  TO anon, authenticated
  USING (activo = true);

CREATE POLICY interno_all_comunidad ON comunidad_fotos
  FOR ALL
  TO authenticated
  USING (get_rol() IN ('master', 'empleado'));
