CREATE TABLE banners (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  url TEXT NOT NULL,
  titulo TEXT,
  link_url TEXT,
  activo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE banners ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read_banners ON banners
  FOR SELECT
  TO anon, authenticated
  USING (activo = true);

CREATE POLICY interno_all_banners ON banners
  FOR ALL
  TO authenticated
  USING (get_rol() IN ('master', 'empleado'));
